package google

const (
    ATOM_CATEGORY_SCHEME_KIND = "http://schemas.google.com/g/2005#kind"
    ATOM_CATEGORY_TERM_CONTACT = "http://schemas.google.com/contact/2008#contact"
    
    REL_WORK = "http://schemas.google.com/g/2005#work"
    REL_HOME = "http://schemas.google.com/g/2005#home"
    REL_OTHER = "http://schemas.google.com/g/2005#other"
    
    REL_MOBILE = "http://schemas.google.com/g/2005#mobile"
    REL_NETMEETING = "http://schemas.google.com/g/2005#netmeeting"
    
    REL_ASSISTANT = "http://schemas.google.com/g/2005#assistant"
    REL_CALLBACK = "http://schemas.google.com/g/2005#callback"
    REL_CAR = "http://schemas.google.com/g/2005#car"
    REL_COMPANY_MAIN = "http://schemas.google.com/g/2005#company_main"
    REL_FAX = "http://schemas.google.com/g/2005#fax"
    REL_HOME_FAX = "http://schemas.google.com/g/2005#home_fax"
    REL_ISDN = "http://schemas.google.com/g/2005#isdn"
    REL_MAIN = "http://schemas.google.com/g/2005#main"
    REL_OTHER_FAX = "http://schemas.google.com/g/2005#other_fax"
    REL_PAGER = "http://schemas.google.com/g/2005#pager"
    REL_RADIO = "http://schemas.google.com/g/2005#radio"
    REL_TELEX = "http://schemas.google.com/g/2005#telex"
    REL_TTY_TDD = "http://schemas.google.com/g/2005#tty_tdd"
    REL_WORK_FAX = "http://schemas.google.com/g/2005#work_fax"
    REL_WORK_MOBILE = "http://schemas.google.com/g/2005#work_mobile"
    REL_WORK_PAGER = "http://schemas.google.com/g/2005#work_pager"
    
    REL_EVENT_ANNIVERSARY = "anniversary"
    REL_EVENT_OTHER = "other"
    
    REL_EXTERNAL_ID_ACCOUNT = "account"
    REL_EXTERNAL_ID_CUSTOMER = "customer"
    REL_EXTERNAL_ID_NETWORK = "network"
    REL_EXTERNAL_ID_ORGANIZATION = "organization"
    
    REL_JOT_HOME = "home"
    REL_JOT_WORK = "work"
    REL_JOT_OTHER = "other"
    REL_JOT_KEYWORDS = "keywords"
    REL_JOT_USER = "user"
    
    REL_PRIORITY_LOW = "low"
    REL_PRIORITY_NORMAL = "normal"
    REL_PRIORITY_HIGH = "high"
    
    REL_RELATION_ASSISTANT = "assistant"
    REL_RELATION_BROTHER = "brother"
    REL_RELATION_CHILD = "child"
    REL_RELATION_DOMESTIC_PARTNER = "domestic-partner"
    REL_RELATION_FATHER = "father"
    REL_RELATION_FRIEND = "friend"
    REL_RELATION_MANAGER = "manager"
    REL_RELATION_MOTHER = "mother"
    REL_RELATION_PARENT = "parent"
    REL_RELATION_PARTNER = "partner"
    REL_RELATION_REFERRED_BY = "referred-by"
    REL_RELATION_RELATIVE = "relative"
    REL_RELATION_SISTER = "sister"
    REL_RELATION_SPOUSE = "spouse"
    
    REL_SENSITIVITY_CONFIDENTIAL = "confidential"
    REL_SENSITIVITY_NORMAL = "normal"
    REL_SENSITIVITY_PERSONAL = "personal"
    REL_SENSITIVITY_PRIVATE = "private"
    
    REL_WEBSITE_HOME_PAGE = "home-page"
    REL_WEBSITE_BLOG = "blog"
    REL_WEBSITE_PROFILE  = "profile"
    REL_WEBSITE_HOME = "home"
    REL_WEBSITE_WORK = "work"
    REL_WEBSITE_OTHER = "other"
    REL_WEBSITE_FTP = "ftp"
    
    IM_PROTOCOL_AIM = "http://schemas.google.com/g/2005#AIM"
    IM_PROTOCOL_GOOGLE_TALK = "http://schemas.google.com/g/2005#GOOGLE_TALK"
    IM_PROTOCOL_ICQ = "http://schemas.google.com/g/2005#ICQ"
    IM_PROTOCOL_JABBER = "http://schemas.google.com/g/2005#JABBER"
    IM_PROTOCOL_MSN = "http://schemas.google.com/g/2005#MSN"
    IM_PROTOCOL_QQ = "http://schemas.google.com/g/2005#QQ"
    IM_PROTOCOL_SKYPE = "http://schemas.google.com/g/2005#SKYPE"
    IM_PROTOCOL_YAHOO = "http://schemas.google.com/g/2005#YAHOO"
    
    MAILCLASS_LETTERS = "http://schemas.google.com/g/2005#letters"
    MAILCLASS_PARCELS = "http://schemas.google.com/g/2005#parcels"
    MAILCLASS_BOTH = "http://schemas.google.com/g/2005#both"
    MAILCLASS_NEITHER = "http://schemas.google.com/g/2005#neither"
    
    ADDRESS_USAGE_GENERAL = "http://schemas.google.com/g/2005#general"
    ADDRESS_USAGE_LOCAL = "http://schemas.google.com/g/2005#local"
    
    SYSTEM_GROUP_CONTACTS = "Contacts"
    SYSTEM_GROUP_FRIENDS = "Friends"
    SYSTEM_GROUP_FAMILY = "Family"
    SYSTEM_GROUP_COWORKERS = "Coworkers"
    
    GOOGLE_DATETIME_FORMAT = "2006-01-02T15:04:05.000Z"
)